apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Utkursraj/ai-task-processing-platform.git
    targetRevision: HEAD
    path: app/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true